<?php
$certificates = [
 ['title'=>'Master of Information Systems','issuer'=>'Fayoum University','img'=>'master-degree.jpeg'],
 ['title'=>'PhD Research Enrollment','issuer'=>'Fayoum University — Information Systems','img'=>'phd-enrollment.jpeg'],
 ['title'=>'Postgraduate Diploma — Information Systems','issuer'=>'Suez Canal University','img'=>'is-diploma.jpeg'],
 ['title'=>'Android Developer Nanodegree','issuer'=>'Udacity · Co-created with Google','img'=>'android-nanodegree.png'],
 ['title'=>'Developing Android Apps','issuer'=>'Udacity','img'=>'developing-android-apps.png'],
 ['title'=>'Data Analysis Professional Nanodegree','issuer'=>'Udacity','img'=>'data-analysis.png'],
 ['title'=>'Google Africa Scholarship — Android','issuer'=>'Andela Learning Community · Google','img'=>'google-africa.png'],
 ['title'=>'Android Developer Track Tutor','issuer'=>'One Million Arab Coders · Udacity','img'=>'one-million-arab-coders.jpg'],
 ['title'=>'Instructor Appreciation','issuer'=>'Digital Egypt Pioneers Program · MCIT Egypt','img'=>'depi-instructor.png'],
 ['title'=>'Hajj Hackathon','issuer'=>'Saudi Federation for Cybersecurity, Programming & Drones','img'=>'hajj-hackathon.png'],
 ['title'=>'Guinness World Records Participation','issuer'=>'Most participants in a hackathon · 2018','img'=>'guinness.jpg'],
 ['title'=>'Academic Test of English','issuer'=>'Tanta University · Score 513','img'=>'toefl-tanta.jpeg'],
 ['title'=>'English Conversation — CON3','issuer'=>'English Certificate','img'=>'english-conversation.jpeg'],
 ['title'=>'Train The Trainers','issuer'=>'International Training License','img'=>'itl-trainer.jpg'],
 ['title'=>'Introduction to Web Development','issuer'=>'Microsoft Official Course','img'=>'microsoft-intro-web.jpg'],
 ['title'=>'MCTS Web Developer 4','issuer'=>'National Education Network','img'=>'mcts-web-developer.jpg'],
 ['title'=>'Developing Web Applications','issuer'=>'Microsoft Official Course','img'=>'microsoft-web-apps.jpg'],
 ['title'=>'Developing Data Access Solutions','issuer'=>'Microsoft Official Course','img'=>'microsoft-data-access.jpg'],
];
$videos = [
 ['title'=>'Master’s Degree Award Moment','desc'=>'Academic milestone and postgraduate journey.','id'=>'cTyQPL-En1k'],
 ['title'=>'Digital Egypt Pioneers — Teaching','desc'=>'A teaching session from the Digital Egypt Pioneers initiative.','id'=>'UR8UhoV1hqU'],
 ['title'=>'Computer Programming Scholarship — North Sinai','desc'=>'Programming fundamentals training at North Sinai Governorate.','id'=>'c8EjlaKX-LQ'],
 ['title'=>'TalabStation Project','desc'=>'A software product demonstration from my mobile development work.','id'=>'cSO9QyOF_t0'],
 ['title'=>'AI Habit Recommendation System','desc'=>'Machine learning and deep learning for personalized habit recommendations.','id'=>'T6oLDxeGRxY'],
 ['title'=>'Mashe Application','desc'=>'Mobile application development walkthrough.','id'=>'rs2PxXLSU7c'],
];
$studentProjects = ['iiKF_p7hA5Q','o59vXvxOXb0','6l0Ae4wnsck','xSAWs_RSD_8','4N8JrtJmzNI','FzaQAgf72o0'];
?>
<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Mohamed Atef | Software Engineer · Researcher · Instructor</title>
<meta name="description" content="Portfolio of Mohamed Atef — senior software engineer, Android/mobile developer, researcher and instructor. Software projects, research, teaching, videos and professional credentials.">
<meta property="og:title" content="Mohamed Atef — Software Engineering Portfolio"><meta property="og:description" content="Software engineering, Android, research, teaching and technology contributions."><meta property="og:image" content="assets/images/profile.png"><meta name="theme-color" content="#07111f">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Manrope:wght@600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="style.css">
</head><body>
<header class="nav"><div class="container nav-inner"><a class="brand" href="#top"><span>MA</span> Mohamed Atef</a><button class="menu" aria-label="Open navigation">☰</button><nav><a href="#work">Work</a><a href="#research">Research</a><a href="#teaching">Teaching</a><a href="#credentials">Credentials</a><a href="#salary">Market Data</a></nav><a class="nav-cta" href="mailto:contact@example.com">Contact</a></div></header>
<main id="top">
<section class="hero"><div class="hero-glow"></div><div class="container hero-grid"><div class="hero-copy"><div class="eyebrow">SOFTWARE ENGINEERING · RESEARCH · EDUCATION</div><h1>Building software.<br><span>Sharing knowledge.</span><br>Creating impact.</h1><p class="lead">Senior Software Engineer and Android specialist with a career spanning software development, applied research, technical instruction and developer mentorship.</p><div class="actions"><a class="btn primary" href="#work">Explore my work →</a><a class="btn ghost" href="https://github.com/Prof-MohamedAtef" target="_blank" rel="noopener">GitHub ↗</a><a class="btn ghost" href="https://www.linkedin.com/in/mobile-developer-atef/" target="_blank" rel="noopener">LinkedIn ↗</a></div><div class="micro">Android · Kotlin · Java · Flutter · Backend · Machine Learning · IoT</div></div><div class="portrait-wrap"><div class="portrait-ring"><img src="assets/images/profile.png" alt="Mohamed Atef speaking at a lectern"></div><div class="float-card"><strong>10+ years</strong><span>Technology & teaching experience</span></div></div></div></section>
<section class="proof"><div class="container proof-grid"><div><strong>Master’s</strong><span>Information Systems</span></div><div><strong>PhD Researcher</strong><span>Information Systems</span></div><div><strong>DEPI Instructor</strong><span>Digital Egypt Pioneers</span></div><div><strong>Guinness Event</strong><span>Hajj Hackathon 2018</span></div><div><strong>15+ Android</strong><span>Native portfolio apps</span></div></div></section>
<section class="section" id="about"><div class="container split"><div><div class="eyebrow">ABOUT</div><h2>Engineering products and helping developers grow.</h2></div><div class="copy"><p>My work sits at the intersection of <b>mobile software engineering, applied research and technical education</b>. I have built production Android and Flutter applications, worked with backend systems, researched IoT and machine-learning problems, and taught programming to developers and students.</p><p>This portfolio brings together selected software work, academic research, public tutorials, student projects and professional credentials.</p></div></div></section>
<section class="section dark" id="work"><div class="container"><div class="section-head"><div><div class="eyebrow">SELECTED WORK</div><h2>Software built for real users.</h2></div><p>Mobile engineering, product development and intelligent systems.</p></div><div class="project-grid"><article class="project featured"><div class="project-no">01</div><div><span class="pill">Mobile · Production</span><h3>TalabStation</h3><p>Mobile application work spanning Flutter, Firebase, authentication, location, background services and real-time notifications.</p><a href="https://www.youtube.com/watch?v=cSO9QyOF_t0" target="_blank" rel="noopener">Watch project ↗</a></div></article><article class="project"><div class="project-no">02</div><div><span class="pill">AI · ML</span><h3>Habit Recommendation System</h3><p>An intelligent recommendation concept using machine learning and deep learning to suggest suitable daily habits.</p><a href="https://www.youtube.com/watch?v=T6oLDxeGRxY&list=PLcyv7wxznokLVZqUFcatqOAeDi9n_8Esj" target="_blank" rel="noopener">Watch series ↗</a></div></article><article class="project"><div class="project-no">03</div><div><span class="pill">Mobile · Commerce</span><h3>Electronic Book Marketplace</h3><p>A mobile-based system for buying and selling books, presented as a practical software-development teaching project.</p><a href="https://www.youtube.com/watch?v=PAV-KyCUXn0&list=PLcyv7wxznokJkkQyryJ4C7KEQpYkKUPjE" target="_blank" rel="noopener">Watch series ↗</a></div></article></div></div></section>
<section class="section" id="research"><div class="container"><div class="research-card"><div><div class="eyebrow">RESEARCH</div><h2>Fuel Consumption Prediction Model using Machine Learning</h2><p>Published research investigating machine-learning approaches for vehicle fuel-consumption prediction, extending my academic work in information systems, IoT and data-driven transportation.</p><div class="actions"><a class="btn primary" href="https://thesai.org/Publications/ViewPaper?Volume=12&Issue=11&Code=IJACSA&SerialNo=46" target="_blank" rel="noopener">Read publication ↗</a><a class="btn ghost light" href="#credentials">Academic credentials</a></div></div><div class="research-mark">R<span>²</span><small>Applied ML research</small></div></div></div></section>
<section class="section soft" id="teaching"><div class="container"><div class="section-head"><div><div class="eyebrow">TEACHING & KNOWLEDGE SHARING</div><h2>From classrooms to YouTube.</h2></div><p>Programming education, mentorship and practical project guidance.</p></div><div class="video-grid"><?php foreach($videos as $v): ?><article class="video-card"><div class="video"><iframe loading="lazy" src="https://www.youtube-nocookie.com/embed/<?=htmlspecialchars($v['id'])?>" title="<?=htmlspecialchars($v['title'])?>" allowfullscreen></iframe></div><div class="video-body"><h3><?=htmlspecialchars($v['title'])?></h3><p><?=htmlspecialchars($v['desc'])?></p></div></article><?php endforeach; ?></div><div class="playlist-row"><a href="https://www.youtube.com/playlist?list=PLcyv7wxznokLTEDaYBp2rBEgW1SPOxG8N" target="_blank">Android tutorials ↗</a><a href="https://www.youtube.com/watch?v=ezBNwdkB5c4&list=PLcyv7wxznokIx3OXtwgycTQJ9TzK830zV" target="_blank">Programming training ↗</a><a href="https://www.youtube.com/watch?v=9-_0SZXUhOg&list=PLcyv7wxznokL0Ym14LdsHFbOhBoVMJPY3" target="_blank">Uber app course ↗</a><a href="https://www.youtube.com/watch?v=UafdflA5AY4&list=PLcyv7wxznokKUnALa3cM1N3_k78yRg2iP" target="_blank">Binary division ↗</a></div></div></section>
<section class="section" id="students"><div class="container"><div class="section-head"><div><div class="eyebrow">MENTORSHIP</div><h2>Selected student graduation projects.</h2></div><p>Examples of projects developed by students under my instruction and guidance.</p></div><div class="student-grid"><?php foreach($studentProjects as $i=>$id): ?><a class="student" href="https://www.youtube.com/watch?v=<?=$id?>" target="_blank"><span>0<?=$i+1?></span><b>Graduation Project</b><em>Watch on YouTube ↗</em></a><?php endforeach; ?></div></div></section>
<section class="section dark" id="credentials"><div class="container"><div class="section-head"><div><div class="eyebrow">CREDENTIALS & ACHIEVEMENTS</div><h2>Continuous learning, research and contribution.</h2></div><p>Duplicate uploads have been intentionally removed. Click any credential to inspect it.</p></div><div class="cert-grid"><?php foreach($certificates as $c): ?><button class="cert" data-img="assets/certificates/<?=htmlspecialchars($c['img'])?>" data-title="<?=htmlspecialchars($c['title'])?>"><img loading="lazy" src="assets/certificates/<?=htmlspecialchars($c['img'])?>" alt="<?=htmlspecialchars($c['title'])?>"><span><b><?=htmlspecialchars($c['title'])?></b><small><?=htmlspecialchars($c['issuer'])?></small></span></button><?php endforeach; ?></div><p class="privacy-note">For privacy, identity documents and unnecessary personal identifiers are not published in this portfolio.</p></div></section>
<section class="section" id="salary"><div class="container"><div class="section-head"><div><div class="eyebrow">ENGINEERING MARKET CONTEXT</div><h2>Developer salary benchmarks in Egypt.</h2></div><p>Public Glassdoor estimates — market context only, not my personal compensation.</p></div><div class="salary-grid"><article><span>Software Engineer</span><strong>EGP 14K<small>/mo median</small></strong><p>Estimated total pay range: EGP 8K–31K/month.</p><a href="https://www.glassdoor.com/Salaries/egypt-software-engineer-salary-SRCH_IL.0,5_IN69_KO6,23.htm" target="_blank">Glassdoor source ↗</a></article><article><span>Senior Software Engineer</span><strong>EGP 20K<small>/mo median</small></strong><p>Estimated total pay range: EGP 11K–35K/month.</p><a href="https://www.glassdoor.com/Salaries/egypt-senior-software-engineer-salary-SRCH_IL.0,5_IN69_KO6,30.htm" target="_blank">Glassdoor source ↗</a></article><article><span>Android Developer</span><strong>EGP 17K<small>/mo median</small></strong><p>Estimated total pay range: EGP 11K–24K/month.</p><a href="https://www.glassdoor.com/Salaries/egypt-android-developer-salary-SRCH_IL.0,5_IN69_KO6,23.htm" target="_blank">Glassdoor source ↗</a></article></div><p class="salary-note">Figures shown as observed in September 2026 and may change as Glassdoor receives new salary submissions.</p></div></section>
<section class="cta"><div class="container cta-inner"><div><div class="eyebrow">LET’S CONNECT</div><h2>Software engineering, research or technical education.</h2></div><div class="actions"><a class="btn white" href="https://github.com/Prof-MohamedAtef" target="_blank">GitHub ↗</a><a class="btn outline-white" href="https://www.linkedin.com/in/mobile-developer-atef/" target="_blank">LinkedIn ↗</a></div></div></section>
</main><footer><div class="container"><b>Mohamed Atef</b><span>Software Engineer · Researcher · Instructor</span><small>© <?=date('Y')?>. Portfolio.</small></div></footer>
<div class="modal" id="modal" aria-hidden="true"><button class="modal-close" aria-label="Close">×</button><div class="modal-box"><img id="modalImg" alt="Certificate preview"><h3 id="modalTitle"></h3></div></div>
<script src="script.js"></script></body></html>
