<?php
$certificates = [
 ['title'=>'Master of Information Systems — English','issuer'=>'Fayoum University','img'=>'master-degree.jpeg'],
 ['title'=>'Master of Information Systems — Arabic','issuer'=>'Fayoum University','img'=>'master-degree-arabic.jpeg'],
 ['title'=>'PhD Research Enrollment','issuer'=>'Fayoum University — Information Systems','img'=>'phd-enrollment.jpeg'],
 ['title'=>'Postgraduate Diploma — Information Systems','issuer'=>'Suez Canal University','img'=>'is-diploma.jpeg'],
 ['title'=>'Postgraduate Diploma — Degree Report','issuer'=>'Suez Canal University · Faculty of Computers & Information','img'=>'postgraduate-diploma-grades-arabic.jpg'],
 ['title'=>'Android Developer Nanodegree','issuer'=>'Udacity · Co-created with Google','img'=>'android-nanodegree.png'],
 ['title'=>'Developing Android Apps','issuer'=>'Udacity','img'=>'developing-android-apps-mal.jpg'],
 ['title'=>'Data Analysis Professional Nanodegree','issuer'=>'Udacity','img'=>'data-analysis.png'],
 ['title'=>'Google Africa Scholarship — Android','issuer'=>'Andela Learning Community · Google','img'=>'google-africa.png'],
 ['title'=>'Android Developer Track Tutor','issuer'=>'One Million Arab Coders · Udacity','img'=>'one-million-arab-coders.jpg'],
 ['title'=>'Instructor Appreciation','issuer'=>'Digital Egypt Pioneers Program · MCIT Egypt','img'=>'depi-instructor-latest.png'],
 ['title'=>'Hajj Hackathon','issuer'=>'Saudi Federation for Cybersecurity, Programming & Drones','img'=>'hajj-hackathon-latest.png'],
 ['title'=>'Guinness World Records Participation','issuer'=>'Most participants in a hackathon · 2018','img'=>'guinness-latest.png'],
 ['title'=>'Guinness World Records — Certificate & Recognition Letter','issuer'=>'Official participation certificate · Hajj Hackathon 2018','img'=>'guinness-full-certificate.jpg'],
 ['title'=>'Academic Test of English','issuer'=>'Tanta University · Score 513','img'=>'toefl-tanta.jpeg'],
 ['title'=>'English Conversation — CON3','issuer'=>'English Certificate','img'=>'english-conversation.jpeg'],
 ['title'=>'Train The Trainers','issuer'=>'International Training License','img'=>'itl-trainer.jpg'],
 ['title'=>'Introduction to Web Development','issuer'=>'Microsoft Official Course','img'=>'microsoft-intro-web.jpg'],
 ['title'=>'MCTS Web Developer 4','issuer'=>'National Education Network','img'=>'mcts-web-developer.jpg'],
 ['title'=>'Developing Web Applications','issuer'=>'Microsoft Official Course','img'=>'microsoft-web-apps.jpg'],
 ['title'=>'Developing Data Access Solutions','issuer'=>'Microsoft Official Course','img'=>'microsoft-data-access.jpg'],
 ['title'=>'Infrastructure & Security — Forensics Investigator','issuer'=>'Digital Egypt Pioneers Program · MCIT Egypt · Jun–Dec 2025','img'=>'depi-forensics.png'],
 ['title'=>'Software Fundamentals Program','issuer'=>'Information Technology Institute (ITI) · MCIT Egypt · 2021–2022','img'=>'certificate-12.jpg'],
 ['title'=>'Cyber Security Training Diploma — 35 Hours','issuer'=>'American Board of Professional Studies · May 2025','img'=>'certificate-13.jpg'],
 ['title'=>'Cyber Security — Excellent Grade','issuer'=>'Egyptian Science House · May 2025','img'=>'certificate-14.jpg'],
 ['title'=>'Cybersecurity & Securing Accounts and Information','issuer'=>'Arab Group for Studies · Sep–Oct 2024','img'=>'certificate-15.jpg'],
 ['title'=>'Introduction to Cybersecurity & Cybersecurity Domains','issuer'=>'Arab Group for Studies · 20 training hours · 2024','img'=>'certificate-16.jpg'],
 ['title'=>'Social Engineering, Phishing & Fraud','issuer'=>'Arab Group for Studies · 20 training hours · 2024','img'=>'certificate-17.jpg'],
 ['title'=>'Malware Attacks & Personal Protection','issuer'=>'Arab Group for Studies · 20 training hours · 2024','img'=>'certificate-18.jpg'],
 ['title'=>'Cyber Security and Securing Accounts & Information — Completion','issuer'=>'Arab Group for Studies · Class of October 2024','img'=>'certificate-19.jpg'],
 ['title'=>'Advanced Cybersecurity & Securing Accounts and Information','issuer'=>'Security Institute for Human Development · Ministry of Interior · 2024','img'=>'certificate-20.jpg'],
 ['title'=>'Short Educational Course for Decision Makers','issuer'=>'Nasser Higher Military Academy / National Defense College · Nov 2024','img'=>'certificate-21.jpg'],
 ['title'=>'Future Leaders Preparation Program','issuer'=>'National Training & Education Council · Dec 2024','img'=>'certificate-22.jpg'],
 ['title'=>'Certificate of Recognition — Top-performing DEPI Student','issuer'=>'Digital Egypt Pioneers · MCIT Egypt','img'=>'certificate-23.jpg'],
];
$certificateCount = count($certificates);
$videos = [
 ['title'=>'Master’s Degree Award Moment','desc'=>'Academic milestone and postgraduate journey.','id'=>'cTyQPL-En1k'],
 ['title'=>'Digital Egypt Pioneers — Teaching','desc'=>'A teaching session from the Digital Egypt Pioneers initiative.','id'=>'UR8UhoV1hqU'],
 ['title'=>'Computer Programming Scholarship — North Sinai','desc'=>'Programming fundamentals training at North Sinai Governorate.','id'=>'c8EjlaKX-LQ'],
 ['title'=>'TalabStation Project','desc'=>'A software product demonstration from my mobile development work.','id'=>'cSO9QyOF_t0'],
 ['title'=>'AI Habit Recommendation System','desc'=>'Machine learning and deep learning for personalized habit recommendations.','id'=>'T6oLDxeGRxY'],
 ['title'=>'Mashe Application','desc'=>'Mobile application development walkthrough.','id'=>'rs2PxXLSU7c'],
 ['title'=>'Robotics Course for Children','desc'=>'Hands-on robotics and programming course for children.','id'=>'LJ3EyvvWglo'],
];
$studentProjects = ['iiKF_p7hA5Q','o59vXvxOXb0','6l0Ae4wnsck','xSAWs_RSD_8','4N8JrtJmzNI','FzaQAgf72o0'];
?>
<!doctype html><html lang="en" dir="ltr"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Mohamed Atef | Software Engineer · Researcher · Instructor</title>
<meta name="description" content="Portfolio of Mohamed Atef — senior software engineer, Android/mobile developer, researcher and instructor. Software projects, research, teaching, videos and professional credentials.">
<meta property="og:title" content="Mohamed Atef — Software Engineering Portfolio"><meta property="og:description" content="Software engineering, Android, research, teaching and technology contributions."><meta property="og:image" content="assets/images/profile.png"><meta name="theme-color" content="#07111f">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Manrope:wght@600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="style.css">
</head><body>
<header class="nav"><div class="container nav-inner"><a class="brand" href="#top"><span>MA</span> Mohamed Atef</a><button class="menu" aria-label="Open navigation">☰</button><nav><a href="#work" data-i18n="navWork">Work</a><a href="#research" data-i18n="navResearch">Research</a><a href="#teaching" data-i18n="navTeaching">Teaching</a><a href="#experience" data-i18n="navExperience">Experience Proof</a><a href="#credentials" data-i18n="navCredentials">Credentials</a><a href="#salary" data-i18n="navMarket">Market Data</a></nav><button id="langToggle" class="lang-toggle" type="button">العربية</button><a class="nav-cta" href="mailto:contact@example.com">Contact</a></div></header>
<main id="top">
<section class="hero"><div class="hero-glow"></div><div class="container hero-grid"><div class="hero-copy"><div class="eyebrow">SOFTWARE ENGINEERING · RESEARCH · EDUCATION</div><h1>Building software.<br><span>Sharing knowledge.</span><br>Creating impact.</h1><p class="lead">Senior Software Engineer and Android specialist with a career spanning software development, applied research, technical instruction and developer mentorship.</p><div class="actions"><a class="btn primary" href="#work">Explore my work →</a><a class="btn ghost" href="https://github.com/Prof-MohamedAtef" target="_blank" rel="noopener">GitHub ↗</a><a class="btn ghost" href="https://www.linkedin.com/in/mobile-developer-atef/" target="_blank" rel="noopener">LinkedIn ↗</a></div><div class="micro">Android · Kotlin · Java · Flutter · Backend · Machine Learning · IoT</div></div><div class="portrait-wrap"><div class="portrait-ring"><img src="assets/images/profile.png" alt="Mohamed Atef speaking at a lectern"></div><div class="float-card"><strong>10+ years</strong><span>Technology & teaching experience</span></div></div></div></section>
<section class="proof"><div class="container proof-grid"><div><strong>Master’s</strong><span>Information Systems</span></div><div><strong>PhD Researcher</strong><span>Information Systems</span></div><div><strong>DEPI Instructor</strong><span>Digital Egypt Pioneers</span></div><div><strong>Guinness Event</strong><span>Hajj Hackathon 2018</span></div><div><strong>15+ Android</strong><span>Native portfolio apps</span></div><div class="certificate-proof"><strong><span class="certificate-number"><?= $certificateCount ?></span> Certificates</strong><span>Credentials & achievements</span></div></div></section>
<section class="section" id="about"><div class="container split"><div><div class="eyebrow">ABOUT</div><h2>Engineering products and helping developers grow.</h2></div><div class="copy"><p>My work sits at the intersection of <b>mobile software engineering, applied research and technical education</b>. I have built production Android and Flutter applications, worked with backend systems, researched IoT and machine-learning problems, and taught programming to developers and students.</p><p>This portfolio brings together selected software work, academic research, public tutorials, student projects and professional credentials.</p></div></div></section>
<section class="section dark" id="work"><div class="container"><div class="section-head"><div><div class="eyebrow">SELECTED WORK</div><h2>Software built for real users.</h2></div><p>Mobile engineering, product development and intelligent systems.</p></div><div class="project-grid"><article class="project featured"><div class="project-no">01</div><div><span class="pill">Mobile · Production</span><h3>TalabStation</h3><p>Mobile application work spanning Flutter, Firebase, authentication, location, background services and real-time notifications.</p><a href="https://www.youtube.com/watch?v=cSO9QyOF_t0" target="_blank" rel="noopener">Watch project ↗</a></div></article><article class="project"><div class="project-no">02</div><div><span class="pill">AI · ML</span><h3>Habit Recommendation System</h3><p>An intelligent recommendation concept using machine learning and deep learning to suggest suitable daily habits.</p><a href="https://www.youtube.com/watch?v=T6oLDxeGRxY&list=PLcyv7wxznokLVZqUFcatqOAeDi9n_8Esj" target="_blank" rel="noopener">Watch series ↗</a></div></article><article class="project"><div class="project-no">03</div><div><span class="pill">Mobile · Commerce</span><h3>Electronic Book Marketplace</h3><p>A mobile-based system for buying and selling books, presented as a practical software-development teaching project.</p><a href="https://www.youtube.com/watch?v=PAV-KyCUXn0&list=PLcyv7wxznokJkkQyryJ4C7KEQpYkKUPjE" target="_blank" rel="noopener">Watch series ↗</a></div></article></div></div></section>
<section class="section" id="research"><div class="container"><div class="research-card"><div><div class="eyebrow">RESEARCH</div><h2>Fuel Consumption Prediction Model using Machine Learning</h2><p>Published research investigating machine-learning approaches for vehicle fuel-consumption prediction, extending my academic work in information systems, IoT and data-driven transportation.</p><div class="actions"><a class="btn primary" href="https://thesai.org/Publications/ViewPaper?Volume=12&Issue=11&Code=IJACSA&SerialNo=46" target="_blank" rel="noopener">Read publication ↗</a><a class="btn ghost light" href="#credentials">Academic credentials</a></div></div><div class="research-mark">R<span>²</span><small>Applied ML research</small></div></div></div></section>
<section class="section soft" id="teaching"><div class="container"><div class="section-head"><div><div class="eyebrow">TEACHING & KNOWLEDGE SHARING</div><h2>From classrooms to YouTube.</h2></div><p>Programming education, mentorship and practical project guidance.</p></div><div class="video-grid"><?php foreach($videos as $v): ?><article class="video-card"><div class="video"><iframe loading="lazy" src="https://www.youtube-nocookie.com/embed/<?=htmlspecialchars($v['id'])?>" title="<?=htmlspecialchars($v['title'])?>" allowfullscreen></iframe></div><div class="video-body"><h3><?=htmlspecialchars($v['title'])?></h3><p><?=htmlspecialchars($v['desc'])?></p></div></article><?php endforeach; ?></div><div class="playlist-row"><a href="https://www.youtube.com/playlist?list=PLcyv7wxznokLTEDaYBp2rBEgW1SPOxG8N" target="_blank">Android tutorials ↗</a><a href="https://www.youtube.com/watch?v=ezBNwdkB5c4&list=PLcyv7wxznokIx3OXtwgycTQJ9TzK830zV" target="_blank">Programming training ↗</a><a href="https://www.youtube.com/watch?v=9-_0SZXUhOg&list=PLcyv7wxznokL0Ym14LdsHFbOhBoVMJPY3" target="_blank">Uber app course ↗</a><a href="https://www.youtube.com/watch?v=UafdflA5AY4&list=PLcyv7wxznokKUnALa3cM1N3_k78yRg2iP" target="_blank">Binary division ↗</a></div></div></section>
<section class="section" id="students"><div class="container"><div class="section-head"><div><div class="eyebrow">MENTORSHIP</div><h2>Selected student graduation projects.</h2></div><p>Examples of projects developed by students under my instruction and guidance.</p></div><div class="student-grid"><?php foreach($studentProjects as $i=>$id): ?><a class="student" href="https://www.youtube.com/watch?v=<?=$id?>" target="_blank"><span>0<?=$i+1?></span><b>Graduation Project</b><em>Watch on YouTube ↗</em></a><?php endforeach; ?></div></div></section>

<section class="section soft" id="experience"><div class="container"><div class="section-head"><div><div class="eyebrow" data-i18n="expEyebrow">VERIFIED PROFESSIONAL EXPERIENCE</div><h2 data-i18n="expTitle">Employment agreements & experience evidence.</h2></div><p data-i18n="expLead">Selected documents supporting professional software-engineering experience. Sensitive identifiers should be reviewed before public deployment.</p></div><div class="evidence-grid">
<article class="evidence-card"><div class="doc-badge">PDF · EN</div><h3 data-i18n="devbudsEn">DevBuds Technologies — Employment Agreement</h3><p data-i18n="devbudsDesc">Remote Android Developer appointment and employment agreement. The document identifies the role as Android Developer and the workplace as home/remote.</p><a href="assets/devbuds-contract-english.pdf" target="_blank" data-i18n="openDocument">Open document ↗</a></article>
<article class="evidence-card"><div class="doc-badge">PDF · AR / EN</div><h3 data-i18n="devbudsBi">DevBuds Technologies — Arabic / English Agreement</h3><p data-i18n="devbudsBiDesc">Bilingual copy of the DevBuds employment documentation for portfolio verification.</p><a href="assets/devbuds-contract-arabic-english.pdf" target="_blank" data-i18n="openDocument">Open document ↗</a></article>
<article class="evidence-card image-evidence"><img src="assets/systems-egypt-experience.jpeg" alt="Systems Egypt employment experience certificate"><div><div class="doc-badge">SYSTEMS EGYPT · 2022–2023</div><h3 data-i18n="systemsTitle">Systems Egypt — Senior Android Developer</h3><p data-i18n="systemsDesc">Experience certificate confirming work as a Senior Android Developer during 2022–2023.</p><a href="assets/systems-egypt-experience.jpeg" target="_blank" data-i18n="viewEvidence">View evidence ↗</a></div></article>
</div></div></section>
<section class="section" id="national-direction"><div class="container"><div class="section-head"><div><div class="eyebrow" data-i18n="nationalEyebrow">EGYPT · DIGITAL SKILLS</div><h2 data-i18n="nationalTitle">Programming and AI as future skills.</h2></div><p data-i18n="nationalLead">Public statements and initiatives highlighting programming, AI and digital-skills education in Egypt.</p></div><div class="video-grid leadership-grid"><article class="video-card"><div class="video"><iframe loading="lazy" src="https://www.youtube-nocookie.com/embed/QxRbye4CFkw" title="President El-Sisi on programming and AI education" allowfullscreen></iframe></div><div class="video-body"><h3 data-i18n="sisiTitle">President Abdel Fattah El-Sisi — Programming & AI Education</h3><p data-i18n="sisiDesc">A 2026 report on the President's direction to keep education aligned with modern programming and AI technologies.</p></div></article><article class="video-card"><div class="video leadership-link"><a href="https://www.cairo24.com/2429672" target="_blank" rel="noopener"><strong data-i18n="madboulyTitle">Prime Minister Mostafa Madbouly — Programming Education</strong><span data-i18n="madboulyDesc">Coverage of his May 2026 school visit and discussion with students about the programming platform. Open video/report ↗</span></a></div></article></div></div></section>
<section class="section dark" id="credentials"><div class="container"><div class="section-head"><div><div class="eyebrow">CREDENTIALS & ACHIEVEMENTS</div><h2>Continuous learning, research and contribution.</h2></div><p class="credential-count"><strong><span class="certificate-number"><?= $certificateCount ?></span> certificates</strong> in this portfolio. Duplicate uploads have been intentionally removed. Click any credential to inspect it.</p></div><div class="cert-grid"><?php foreach($certificates as $c): ?><button class="cert" data-img="assets/certificates/<?=htmlspecialchars($c['img'])?>" data-title="<?=htmlspecialchars($c['title'])?>"><img loading="lazy" src="assets/certificates/<?=htmlspecialchars($c['img'])?>" alt="<?=htmlspecialchars($c['title'])?>"><span><b><?=htmlspecialchars($c['title'])?></b><small><?=htmlspecialchars($c['issuer'])?></small></span></button><?php endforeach; ?></div><p class="privacy-note">For privacy, identity documents and unnecessary personal identifiers are not published in this portfolio.</p></div></section>
<section class="section" id="salary"><div class="container"><div class="section-head"><div><div class="eyebrow" data-i18n="marketEyebrow">SENIOR SOFTWARE ENGINEERING MARKET</div><h2 data-i18n="marketTitle">Higher-opportunity compensation benchmarks.</h2></div><p data-i18n="marketLead">Senior Software Engineer benchmarks only. Public market data, not my personal compensation.</p></div><div class="salary-grid"><article><span>Remote · Senior Software Engineer</span><strong>$205K<small>/yr avg total comp</small></strong><p>Built In reports about $180,961 average base and $205,221 average total compensation for remote Senior Software Engineers.</p><a href="https://builtin.com/salaries/us/remote/senior-software-engineer" target="_blank">Built In source ↗</a></article><article><span>United States · Senior Software Engineer</span><strong>$250.5K<small>/yr median total comp</small></strong><p>Levels.fyi reports a U.S. median total compensation of about $250,500 for Senior Software Engineers.</p><a href="https://www.levels.fyi/t/software-engineer/levels/senior/locations/united-states" target="_blank">Levels.fyi source ↗</a></article><article><span>High-end example · UiPath Senior SWE</span><strong>$348.5K<small>/yr avg total comp</small></strong><p>A higher-end Senior Software Engineer example from Levels.fyi, combining base, stock and bonus.</p><a href="https://www.levels.fyi/companies/uipath/salaries/software-engineer/levels/senior-software-engineer/locations/united-states" target="_blank">Levels.fyi source ↗</a></article></div><p class="salary-note" data-i18n="marketNote">Observed September 2026. Compensation varies by location, company, level, equity and eligibility; these figures do not imply that every remote role is accessible from every country.</p></div></section>
<section class="cta"><div class="container cta-inner"><div><div class="eyebrow">LET’S CONNECT</div><h2>Software engineering, research or technical education.</h2></div><div class="actions"><a class="btn white" href="https://github.com/Prof-MohamedAtef" target="_blank">GitHub ↗</a><a class="btn outline-white" href="https://www.linkedin.com/in/mobile-developer-atef/" target="_blank">LinkedIn ↗</a></div></div></section>
</main><footer><div class="container"><b>Mohamed Atef</b><span>Software Engineer · Researcher · Instructor</span><small>© <?=date('Y')?>. Portfolio.</small></div></footer>
<div class="modal" id="modal" aria-hidden="true"><button class="modal-close" aria-label="Close">×</button><div class="modal-box"><img id="modalImg" alt="Certificate preview"><h3 id="modalTitle"></h3></div></div>
<script src="script.js"></script></body></html>
