const menu=document.querySelector('.menu'),nav=document.querySelector('.nav');menu?.addEventListener('click',()=>nav.classList.toggle('open'));document.querySelectorAll('.nav nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const modal=document.querySelector('#modal'),img=document.querySelector('#modalImg'),title=document.querySelector('#modalTitle');document.querySelectorAll('.cert').forEach(c=>c.addEventListener('click',()=>{img.src=c.dataset.img;title.textContent=c.dataset.title;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}));function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');img.src=''}document.querySelector('.modal-close').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});

const i18n = {
 en:{navWork:'Work',navResearch:'Research',navTeaching:'Teaching',navExperience:'Experience Proof',navCredentials:'Credentials',navMarket:'Market Data',expEyebrow:'VERIFIED PROFESSIONAL EXPERIENCE',expTitle:'Employment agreements & experience evidence.',expLead:'Selected documents supporting professional software-engineering experience. Sensitive identifiers should be reviewed before public deployment.',devbudsEn:'DevBuds Technologies — Employment Agreement',devbudsDesc:'Remote Android Developer appointment and employment agreement. The document identifies the role as Android Developer and the workplace as home/remote.',devbudsBi:'DevBuds Technologies — Arabic / English Agreement',devbudsBiDesc:'Bilingual copy of the DevBuds employment documentation for portfolio verification.',openDocument:'Open document ↗',systemsTitle:'Systems Egypt — Senior Android Developer',systemsDesc:'Experience certificate confirming work as a Senior Android Developer during 2022–2023.',viewEvidence:'View evidence ↗',nationalEyebrow:'EGYPT · DIGITAL SKILLS',nationalTitle:'Programming and AI as future skills.',nationalLead:'Public statements and initiatives highlighting programming, AI and digital-skills education in Egypt.',sisiTitle:'President Abdel Fattah El-Sisi — Programming & AI Education',sisiDesc:"A 2026 report on the President's direction to keep education aligned with modern programming and AI technologies.",madboulyTitle:'Prime Minister Mostafa Madbouly — Programming Education',madboulyDesc:'Coverage of his May 2026 school visit and discussion with students about the programming platform. Open video/report ↗',marketEyebrow:'SENIOR SOFTWARE ENGINEERING MARKET',marketTitle:'Higher-opportunity compensation benchmarks.',marketLead:'Senior Software Engineer benchmarks only. Public market data, not my personal compensation.',marketNote:'Observed September 2026. Compensation varies by location, company, level, equity and eligibility; these figures do not imply that every remote role is accessible from every country.'},
 ar:{navWork:'الأعمال',navResearch:'البحث العلمي',navTeaching:'التدريب',navExperience:'إثبات الخبرة',navCredentials:'الشهادات',navMarket:'سوق العمل',expEyebrow:'الخبرة المهنية الموثقة',expTitle:'عقود العمل ومستندات إثبات الخبرة.',expLead:'مستندات مختارة تدعم الخبرة المهنية في هندسة البرمجيات. يُنصح بمراجعة البيانات الشخصية الحساسة قبل النشر العام.',devbudsEn:'DevBuds Technologies — عقد العمل باللغة الإنجليزية',devbudsDesc:'خطاب تعيين وعقد عمل عن بُعد بوظيفة Android Developer، ويوضح المستند أن مقر العمل من المنزل.',devbudsBi:'DevBuds Technologies — العقد العربي / الإنجليزي',devbudsBiDesc:'نسخة ثنائية اللغة من مستندات التوظيف لاستخدامها في توثيق الخبرة المهنية.',openDocument:'فتح المستند ↗',systemsTitle:'Systems Egypt — مطور أندرويد أول',systemsDesc:'شهادة خبرة تؤكد العمل بوظيفة Senior Android Developer خلال عامي 2022–2023.',viewEvidence:'عرض المستند ↗',nationalEyebrow:'مصر · المهارات الرقمية',nationalTitle:'البرمجة والذكاء الاصطناعي من مهارات المستقبل.',nationalLead:'تصريحات ومبادرات عامة تسلط الضوء على تعليم البرمجة والذكاء الاصطناعي والمهارات الرقمية في مصر.',sisiTitle:'الرئيس عبد الفتاح السيسي — تعليم البرمجة والذكاء الاصطناعي',sisiDesc:'تقرير لعام 2026 حول التوجيه بمواكبة أحدث تكنولوجيا البرمجة والذكاء الاصطناعي في التعليم.',madboulyTitle:'رئيس الوزراء د. مصطفى مدبولي — تعليم البرمجة',madboulyDesc:'تغطية لزيارته المدرسية في مايو 2026 وحواره مع الطلاب حول منصة البرمجة. فتح الفيديو/التقرير ↗',marketEyebrow:'سوق مهندسي البرمجيات الأوائل',marketTitle:'مؤشرات رواتب لفرص أعلى.',marketLead:'بيانات خاصة بوظائف Senior Software Engineer فقط، وهي بيانات سوق عامة وليست راتبي الشخصي.',marketNote:'البيانات كما ظهرت في سبتمبر 2026. تختلف الرواتب حسب الدولة والشركة والمستوى والأسهم والأهلية، ولا تعني هذه الأرقام أن كل وظيفة عن بُعد متاحة من كل دولة.'}
};
const langBtn=document.getElementById('langToggle');
function setLang(lang){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(i18n[lang][k])el.textContent=i18n[lang][k]});langBtn.textContent=lang==='ar'?'English':'العربية';localStorage.setItem('portfolioLang',lang)}
if(langBtn){let lang=localStorage.getItem('portfolioLang')||'en';setLang(lang);langBtn.addEventListener('click',()=>{lang=document.documentElement.lang==='ar'?'en':'ar';setLang(lang)})}
